# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jgrep < Formula
  desc "Homebrew distibution of jgrep, the ultimate JSON (and YAML) grep`er."
  homepage "https://github.com/frese/jgrep"
  version "0.1.8"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frese/jgrep/releases/download/v0.1.8/jgrep_0.1.8_darwin_x86_64.tar.gz"
      sha256 "54c2d7fa1f5e9dbc7dcdc7e3bb182c83fdd87381f2d480af546b13297b75c0f5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/frese/jgrep/releases/download/v0.1.8/jgrep_0.1.8_linux_x86_64.tar.gz"
      sha256 "b06b274daddccd7206cbde1bdc4164135bf620eeec7c594ba0d81ee7aab3b81a"
    end
  end

  def install
    bin.install "jgrep"
  end
end
