# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jgrep < Formula
  desc "Homebrew distibution of jgrep, the ultimate JSON (and YAML) grep`er."
  homepage "https://github.com/frese/jgrep"
  version "0.1.9"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frese/jgrep/releases/download/v0.1.9/jgrep_0.1.9_darwin_x86_64.tar.gz"
      sha256 "3f83c43b0240b2386ae8fe3f59058ba57308e40c26216ccfe7b40c520d277544"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/frese/jgrep/releases/download/v0.1.9/jgrep_0.1.9_linux_x86_64.tar.gz"
      sha256 "e9c623e0b54612bd2bd8a748064621c20d5c9d19ebea0061d3f544218d91b27c"
    end
  end

  def install
    bin.install "jgrep"
  end
end
