# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jgrep < Formula
  desc "Homebrew distibution of jgrep, the ultimate JSON grep`er."
  homepage "https://github.com/frese/jgrep"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/frese/jgrep/releases/download/v0.1.1/jgrep_0.1.1_darwin_x86_64.tar.gz"
    sha256 "d890ec22a4c6d466e7cb66e8749b7f0a2951027e9a110fda024550e47c67e31d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/frese/jgrep/releases/download/v0.1.1/jgrep_0.1.1_linux_x86_64.tar.gz"
    sha256 "481c2a044cdc12bb8ededce6c70e25b4a6ae9cc0652967463b5066e31d037df0"
  end

  def install
    bin.install "jgrep"
  end
end
